name: Kubernetes deployment
run-name: Deploy Kubernoots config
on: [push]
jobs:
  deploy-k8s:
    runs-on: devsecops
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Aplicar configuração
        run: |
          kubectl -f apply deployment.yaml
